
name: CI/CD Pipeline

on:
  push:
    branches:
      - dev1
  pull_request:
    branches:
      - dev1

jobs:
  build:
    runs-on: ubuntu-latest

    
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run SonarQube Scan
        env:
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
         SONAR_SCANNER_OPTS: -Xmx1024m
        run: |
         sonar-scanner \
          -Dsonar.projectKey=node-web-app \
          -Dsonar.organization=cf-dev \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -X

           
       
      
